(evidence
  (requirement . GUIX-WITNESS-01)
  (implementation . ganaka-wsl)
  (commit . "374c0c4")
  (runner . "guix build -f crates/swarm-node/package.scm --rounds=2")
  (expected . "deterministic store derivation, runnable binary")
  (actual . "/gnu/store/6j2k1gcrsnhbhlj9ms6i8mwxbh5rapyq-swarm-node-0.1.0")
  (result . pass)
  (timestamp . "2026-08-26")
  (note . "Step 4 witness (independent builder): double-round build succeeded, binary smoke-tested (--help runs). DEVIATIONS honestly recorded: (1) --no-substitutes NOT used this pass - dependencies came from local store substitutes; strict no-substitute source build deferred to resource window; (2) current guix revision, not time-machine pinned channels.scm (5375f33). Package definition by wsl-nidana-1 (9404fee)."))
