(cml-export/1
  (contract (major 6) (minor 0))
  (digest "c09f71e1d9e2402b")
  (forms
    (0001 (surfaces (en "quote") (sa "svarūpa") (sym "'") (uk "як-є")) (role syntax) (callable nil))
    (0002 (surfaces (en "atom") (sa "aṇu") (sym ".?") (uk "атом?")) (role primitive) (callable t))
    (0003 (surfaces (en "eq") (sa "abheda") (sym "=?") (uk "тотожне?")) (role primitive) (callable t))
    (0004 (surfaces (en "cons") (sa "saṃyuj") (sym ":") (uk "сполучити")) (role primitive) (callable t))
    (0005 (surfaces (en "car") (sa "ādi") (sym ":п") (uk "перше")) (role primitive) (callable t))
    (0006 (surfaces (en "cdr") (sa "śeṣa") (sym ":р") (uk "решта")) (role primitive) (callable t))
    (0007 (surfaces (en "cond") (sa "anukrama") (sym "?:") (uk "за-умовою")) (role syntax) (callable nil))
    (0010 (surfaces (en "lambda") (uk "функція")) (role syntax) (callable nil))
    (0011 (surfaces (en "define") (uk "визначити")) (role syntax) (callable nil))
    (0012 (surfaces (compat "defmacro-derived") (en "defmacro") (uk "визначити-макрос")) (role syntax) (callable nil))
    (1001 (surfaces (sa "viyoga") (sym "-") (uk "відняти")) (role library) (callable t))))
