(cml-export/1
  (contract (major 6) (minor 0))
  (digest "c49a08f8921e0e13")
  (forms
    (0001 (surfaces (en "quote") (sa "svarūpa") (sym "'") (uk "як-є") (ukr "як-є")) (role syntax) (callable nil))
    (0002 (surfaces (en "atom") (sa "aṇu") (sym ".?") (uk "атом?") (ukr "атом?")) (role primitive) (callable t))
    (0003 (surfaces (en "eq") (sa "abheda") (sym "=?") (uk "тотожне?") (ukr "тотожне?")) (role primitive) (callable t))
    (0004 (surfaces (en "cons") (sa "saṃyuj") (sym ":") (uk "сполучити") (ukr "сполучити")) (role primitive) (callable t))
    (0005 (surfaces (en "car") (sa "ādi") (sym ":п") (uk "перше") (ukr "перше")) (role primitive) (callable t))
    (0006 (surfaces (en "cdr") (sa "śeṣa") (sym ":р") (uk "решта") (ukr "решта")) (role primitive) (callable t))
    (0007 (surfaces (en "cond") (sa "anukrama") (sym "?:") (uk "за-умовою") (ukr "за-умовою")) (role syntax) (callable nil))
    (0010 (surfaces (en "lambda") (uk "функція") (ukr "функція")) (role syntax) (callable nil))
    (0011 (surfaces (en "define") (uk "визначити") (ukr "визначити")) (role syntax) (callable nil))
    (0012 (surfaces (compat "defmacro-derived") (en "defmacro") (uk "визначити-макрос") (ukr "визначити-макрос")) (role syntax) (callable nil))
    (1001 (surfaces (sa "viyoga") (sym "-") (uk "відняти") (ukr "відняти")) (role library) (callable t))))
