; #114/#115 authority inventory projection.
; Lisp reads this as data; CI/host code may transport paths but must not own
; the allow/deny rule. Keep tests/authority-inventory.tsv as the tabular audit
; projection for reviewers.

(authority "crates/my-lisp/tests/witness_authority.rs" observer)
(authority "crates/my-lisp/tests/structural_query_inventory.rs" observer)
(authority "crates/my-lisp/tests/structural_observation_contract.rs" observer)
(authority "crates/my-lisp/tests/exact_q_binary_contract.rs" observer)
(authority "crates/my-lisp/tests/mathematical_result_taxonomy.rs" observer)
(authority "crates/my-lisp/tests/control_dispatch_contract.rs" observer)
(authority "crates/my-lisp/tests/authority_guard_contract.rs" observer)
(authority "crates/my-lisp/tests/mccarthy.rs" semantic-authority)
(authority "crates/my-lisp/tests/ukrainian_api_docs.rs" semantic-authority)
(authority "crates/my-lisp/tests/rivnopravnist_mov.rs" semantic-authority)
(authority "tests/fixtures/authority-guard/forbidden-semantic.rs" semantic-authority)
(authority "tests/fixtures/authority-guard/allowed-mechanism.rs" mechanism)
(authority "crates/my-lisp/tests/skylake_inventory_contract.rs" observer)
(authority "crates/xtask/tests/xed_import_cli.rs" observer)
(authority "crates/xtask/tests/external_oracle_cli.rs" observer)
(authority "crates/my-lisp/tests/machine_noninterference_contract.rs" observer)
(authority "crates/my-lisp/tests/x86_64_lisp_encoder.rs" mechanism)
(authority "crates/xtask/tests/encoder_coverage_cli.rs" observer)
(authority "crates/my-lisp/tests/machine_admission_adversarial.rs" mechanism)
(authority "crates/my-lisp/tests/machine_atoms.rs" mechanism)
(authority "crates/my-lisp/tests/machine_typed_operands.rs" mechanism)
(authority "crates/my-lisp/tests/machine_block_roundtrip.rs" mechanism)
(authority "crates/my-lisp/tests/support/x86_64_block_decoder.rs" mechanism)
(authority "crates/my-lisp/tests/machine_lowering_boundary.rs" observer)
(authority "crates/my-lisp-host/tests/native_lisp_bytes.rs" mechanism)
(authority "crates/my-lisp-host/tests/windows_native_exec_abi.rs" mechanism)
(authority "crates/my-lisp/tests/machine_minimal_profile.rs" observer)
(authority "crates/my-lisp-host/tests/native_cond_profile.rs" mechanism)
(authority "crates/xtask/tests/license_policy.rs" observer)
