((schema . deep-structural-relation/1)
 (operation . equal?)
 (question-domain . structure)
 (result-form . structural-relation)
 (result-values . ((structural-relation same)
                   (structural-relation distinct)))
 (laws .
   ((identity-is-not-structure . t)
    (universal-truth-forbidden . t)
    (canon-zero-may-be-compared-as-structure . t)
    (generic-value-to-bool-forbidden . t)))
 (cases .
   (((left . ())
     (right . ())
     (result . (structural-relation same)))
    ((left . radio)
     (right . radio)
     (result . (structural-relation same)))
    ((left . radio)
     (right . antenna)
     (result . (structural-relation distinct)))
    ((left . (radio antenna))
     (right . (radio antenna))
     (result . (structural-relation same)))
    ((left . (radio antenna))
     (right . (radio signal))
     (result . (structural-relation distinct)))
    ((left . (radio))
     (right . radio)
     (result . (structural-relation distinct))))))
