  (00000000 (sym ()))
  (00000001 (en quote) (uk як-є) (ukr як-є) (sa svarūpa) (sym '))
  (00000010 (en atom) (uk атом?) (ukr атом?) (sa aṇu) (sym .?))
  (00000011 (en eq) (uk тотожне?) (ukr тотожне?) (sa abheda) (sym =?))
  (00000100 (en cons) (uk сполучити) (ukr сполучити) (sa saṃyuj) (sym :))
  (00000101 (en car) (uk перше) (ukr перше) (sa ādi) (sym :п))
  (00000110 (en cdr) (uk решта) (ukr решта) (sa śeṣa) (sym :р))
  (00000111 (en cond) (uk за-умовою) (ukr за-умовою) (sa anukrama) (sym ?:))
  (00001000 (en lambda) (uk функція) (ukr функція) (sa — missing))
  (00001001 (en define) (uk визначити) (ukr визначити) (sa — missing))
  (00001010 (en defmacro) (uk визначити-макрос) (ukr визначити-макрос) (sa — missing) (compat defmacro-derived compatibility-only))
  (00001011 (en def compatibility-only) (uk — compatibility-only) (ukr визначити candidate) (sa — compatibility-only))
  (00001100 (en — missing) (uk додати) (ukr додати) (sa yoga) (sym +))
  (00001101 (en — missing) (uk відняти) (ukr відняти) (sa viyoga) (sym -))
  (00001110 (en — missing) (uk помножити) (ukr помножити) (sa guṇana) (sym *))
  (00001111 (en — missing) (uk поділити) (ukr поділити) (sa haraṇa) (sym /))
  (00010000 (en abs) (uk модуль) (ukr модуль) (sa rūpa candidate))
  (00010001 (en min) (uk найменше) (ukr найменше) (sa alpatara))
  (00010010 (en max) (uk найбільше) (ukr найбільше) (sa brhattara))
  (00010011 (en mod) (uk остача) (ukr остача) (sa avasiṣṭa))
  (00010100 (en quotient) (uk частка) (ukr частка) (sa bhāga))
  (00010101 (en sqrt) (uk корінь) (ukr корінь) (sa mūla))
  (00010110 (en isqrt) (uk цілий-корінь) (ukr цілий-корінь) (sa sakalamūla))
  (00010111 (en min-list) (uk найменше-у-списку) (ukr найменше-у-списку) (sa — missing))
  (00011000 (en max-list) (uk найбільше-у-списку) (ukr найбільше-у-списку) (sa — missing))
  (00011001 (en largest-chunk compatibility-only) (uk — compatibility-only) (ukr найбільший-фрагмент candidate) (sa — compatibility-only))
  (00011010 (en — missing) (uk менше?) (ukr менше?) (sa hīna?) (sym <))
  (00011011 (en — missing) (uk більше?) (ukr більше?) (sa adhika?) (sym >))
  (00011100 (en — missing) (uk рівне?) (ukr рівне?) (sa sama?) (sym =))
  (00011101 (en — missing) (uk не-більше?) (ukr не-більше?) (sa na-adhika? candidate) (sym <=))
  (00011110 (en — missing) (uk не-менше?) (ukr не-менше?) (sa na-hīna? candidate) (sym >=))
  (00011111 (en nondecreasing-from? compatibility-only) (uk — compatibility-only) (ukr неспадне-починаючи-з? candidate) (sa — compatibility-only))
  (00100000 (en nonincreasing-from? compatibility-only) (uk — compatibility-only) (ukr незростаюче-починаючи-з? candidate) (sa — compatibility-only))
  (00100001 (en not) (uk хибне?) (ukr хибне?) (sa na))
  (00100010 (en equal?) (uk однакові?) (ukr однакові?) (sa tulya?))
  (00100011 (en symbol?) (uk символ?) (ukr символ?) (sa nāman?))
  (00100100 (en string?) (uk текст?) (ukr текст?) (sa śabda?))
  (00100101 (en string<?) (uk текст-передує?) (ukr текст-передує?) (sa śabda-hīna? candidate))
  (00100110 (en numeric-buffer?) (uk числовий-буфер?) (ukr числовий-буфер?) (sa — missing))
  (00100111 (en list) (uk список) (ukr список) (sa śreṇī))
  (00101000 (en length) (uk довжина) (ukr довжина) (sa pramāṇa))
  (00101001 (en append) (uk приєднати) (ukr приєднати) (sa saṅkalana))
  (00101010 (en reverse) (uk зворот) (ukr зворот) (sa viloma))
  (00101011 (en nth) (uk елемент-списку-за-індексом) (ukr елемент-списку-за-індексом) (sa kramāṅka))
  (00101100 (en member?) (uk значення-у-списку?) (ukr значення-у-списку?) (sa sambaddha? candidate))
  (00101101 (en assoc) (uk знайти-за-ключем) (ukr знайти-за-ключем) (sa saṃbandha))
  (00101110 (en pair) (uk пара) (ukr пара) (sa dvandva))
  (00101111 (en second) (uk друге) (ukr друге) (sa dvitīya))
  (00110000 (en third) (uk третє) (ukr третє) (sa tṛtīya))
  (00110001 (en fourth) (uk четверте) (ukr четверте) (sa caturtha))
  (00110010 (en fifth) (uk п'яте) (ukr п'яте) (sa pañcama))
  (00110011 (en caar compatibility-only) (uk — compatibility-only) (ukr перше-від-першого candidate) (sa — compatibility-only))
  (00110100 (en cadr compatibility-only) (uk — compatibility-only) (ukr перше-від-решти candidate) (sa — compatibility-only))
  (00110101 (en cddr compatibility-only) (uk — compatibility-only) (ukr решта-від-решти candidate) (sa — compatibility-only))
  (00110110 (en cadddr compatibility-only) (uk — compatibility-only) (ukr перше-після-трьох-решт candidate) (sa — compatibility-only))
  (00110111 (en map) (uk відобразити) (ukr відобразити) (sa āvartana candidate))
  (00111000 (en filter) (uk відсіяти) (ukr відсіяти) (sa kalpana candidate))
  (00111001 (en reduce) (uk згорнути) (ukr згорнути) (sa saṅgraha candidate))
  (00111010 (en string-append) (uk зчепити) (ukr зчепити) (sa śabdasaṃyoga candidate))
  (00111011 (en string-length) (uk довжина-тексту) (ukr довжина-тексту) (sa śabdapramāṇa candidate))
  (00111100 (en string-empty?) (uk текст-порожній?) (ukr порожній-текст?) (sa śūnya?))
  (00111101 (en string-prefix?) (uk префікс-тексту?) (ukr текст-починається-з? candidate) (sa pūrva? candidate))
  (00111110 (en string-contains?) (uk фрагмент-у-тексті?) (ukr фрагмент-у-тексті?) (sa śabdasambaddha? candidate))
  (00111111 (en string-first) (uk перший-символ-тексту) (ukr перший-символ-тексту) (sa prathamavarṇa candidate))
  (01000000 (en string-rest) (uk решта-символів-тексту) (ukr решта-символів-тексту) (sa śeṣavarṇa candidate))
  (01000001 (en string-slice) (uk відрізати) (ukr відрізати) (sa cheda candidate))
  (01000010 (en symbol->string) (uk символ-у-текст) (ukr символ-у-текст) (sa nāman-śabda candidate))
  (01000011 (en string->symbol) (uk текст-у-символ) (ukr текст-у-символ) (sa śabda-nāman candidate))
  (01000100 (en codepoint->string) (uk кодова-точка-у-текст) (ukr кодова-точка-у-текст) (sa varṇa-śabda candidate))
  (01000101 (en string->codepoint) (uk текст-у-кодову-точку) (ukr текст-у-кодову-точку) (sa śabda-varṇa candidate))
  (01000110 (en number->string) (uk число-у-текст) (ukr число-у-текст) (sa saṅkhyā-śabda candidate))
  (01000111 (en digit->string compatibility-only) (uk — compatibility-only) (ukr цифра-у-текст candidate) (sa — compatibility-only))
  (01001000 (en print) (uk друкувати) (ukr друкувати) (sa mudraṇa candidate))
  (01001001 (en princ) (uk показати) (ukr показати) (sa darśana candidate))
  (01001010 (en read) (uk прочитати) (ukr прочитати) (sa pāṭhana candidate))
  (01001011 (en read-all) (uk прочитати-усе) (ukr прочитати-усе) (sa pāṭhana-sarva candidate))
  (01001100 (en write-to-string) (uk значення-у-текст) (ukr значення-у-текст) (sa likhana candidate))
  (01001101 (en eval) (uk обчислити) (ukr обчислити) (sa vicāraṇa candidate))
  (01001110 (en env) (uk середовище) (ukr середовище) (sa āśraya candidate))
  (01001111 (en vector) (uk вектор) (ukr вектор) (sa samūha candidate))
  (01010000 (en make-vector) (uk створити-вектор) (ukr створити-вектор) (sa samūha-nirmāṇa candidate))
  (01010001 (en vector-length) (uk довжина-вектора) (ukr довжина-вектора) (sa samūha-pramāṇa candidate))
  (01010010 (en vector-ref) (uk елемент-вектора) (ukr елемент-вектора) (sa samūha-āvartana candidate))
  (01010011 (en vector-set!) (uk встановити-елемент-вектора!) (ukr встановити-елемент-вектора!) (sa — missing))
  (01010100 (en i32-buffer compatibility-only) (uk — compatibility-only) (ukr буфер-32-бітних-цілих-зі-знаком candidate) (sa — compatibility-only))
  (01010101 (en f32-buffer compatibility-only) (uk — compatibility-only) (ukr буфер-32-бітних-чисел-з-плавною-комою candidate) (sa — compatibility-only))
  (01010110 (en numeric-buffer-type compatibility-only) (uk — compatibility-only) (ukr тип-числового-буфера candidate) (sa — compatibility-only))
  (01010111 (en numeric-buffer-length compatibility-only) (uk — compatibility-only) (ukr довжина-числового-буфера candidate) (sa — compatibility-only))
  (01011000 (en numeric-buffer-ref compatibility-only) (uk — compatibility-only) (ukr елемент-числового-буфера candidate) (sa — compatibility-only))
  (01011001 (en numeric-buffer-map compatibility-only) (uk — compatibility-only) (ukr відобразити-числовий-буфер candidate) (sa — compatibility-only))
  (01011010 (en mono-ns) (uk монотонний-нс) (ukr монотонний-час-у-наносекундах candidate) (sa kāla-mono candidate))
  (01011011 (en unix-time-now) (uk поточний-юнікс-час) (ukr поточний-юнікс-час) (sa kāla-unix candidate))
  (01011100 (en ntp-query-raw compatibility-only) (uk — compatibility-only) (ukr сирий-запит-мережевого-часу candidate) (sa — compatibility-only))
  (01011101 (en timezone-declarations-raw compatibility-only) (uk — compatibility-only) (ukr сирі-декларації-часових-поясів candidate) (sa — compatibility-only))
  (01011110 (en utc-now) (uk поточний-всч) (ukr поточний-всесвітній-координований-час candidate) (sa kāla-adya candidate))
  (01011111 (en utc-from-unix) (uk всч-із-юнікс) (ukr всесвітній-координований-час-із-часу-юнікс candidate) (sa — missing))
  (01100000 (en unix-time-observation->utc) (uk юнікс-спостереження-у-всч) (ukr спостереження-часу-юнікс-у-всесвітній-координований-час candidate) (sa — missing))
  (01100001 (en milliseconds-from-nanoseconds) (uk мілісекунди-із-наносекунд) (ukr мілісекунди-із-наносекунд) (sa kāla-millisecondāni candidate))
  (01100010 (en mono-ms) (uk монотонний-мс) (ukr монотонний-час-у-мілісекундах candidate) (sa kāla-mono-ms candidate))
  (01100011 (en timezone-name) (uk назва-часового-поясу) (ukr назва-часового-поясу) (sa deśa-kāla-nāma candidate))
  (01100100 (en timezone-detect) (uk визначити-часовий-пояс) (ukr визначити-часовий-пояс) (sa deśa-kāla-jñāna candidate))
  (01100101 (en timezone-offset-seconds) (uk зміщення-часового-поясу-в-секундах) (ukr зміщення-часового-поясу-в-секундах) (sa deśa-kāla-śeṣa candidate))
  (01100110 (en deadline-reached?) (uk дедлайн-досягнуто?) (ukr граничний-час-досягнуто? candidate) (sa avadhi-gatā? candidate))
  (01100111 (en deadline-reached-at?) (uk дедлайн-досягнуто-на-момент?) (ukr граничний-час-досягнуто-на-момент? candidate) (sa avadhi-gatā-kadā? candidate))
  (01101000 (en elapsed-ns) (uk минуло-нс) (ukr минуло-наносекунд candidate) (sa atīta-ns candidate))
  (01101001 (en deadline-from) (uk дедлайн-від) (ukr граничний-час-від candidate) (sa avadhi-nirmāṇa candidate))
  (01101010 (en deadline-after-ns) (uk дедлайн-через-нс) (ukr граничний-час-через-наносекунди candidate) (sa avadhi-anantara-ns candidate))
  (01101011 (en internet-time-sync) (uk запитати-інтернет-час) (ukr синхронізувати-час-через-інтернет candidate) (sa — missing))
  (01101100 (en map-empty) (uk порожня-карта) (ukr порожня-карта) (sa kośa-śūnya candidate))
  (01101101 (en map-get) (uk отримати-з-карти) (ukr отримати-з-карти) (sa kośa-grahaṇa candidate))
  (01101110 (en map-insert) (uk вставити-в-карту) (ukr вставити-в-карту) (sa kośa-niveśana candidate))
  (01101111 (en map-contains?) (uk ключ-у-карті?) (ukr ключ-у-карті?) (sa kośa-sambaddha? candidate))
  (01110000 (en map->list) (uk карта-у-список) (ukr карта-у-список) (sa kośa-śreṇī candidate))
  (01110001 (en vec-empty) (uk порожній-вектор) (ukr порожній-вектор) (sa samūha-śūnya candidate))
  (01110010 (en vec-conj) (uk додати-до-вектора) (ukr додати-до-вектора) (sa samūha-yukti candidate))
  (01110011 (en vec-count) (uk розмір-вектора) (ukr розмір-вектора) (sa samūha-gaṇana candidate))
  (01110100 (en vec-nth) (uk елемент-вектора-за-індексом) (ukr елемент-вектора-за-індексом) (sa samūha-kramāṅka candidate))
  (01110101 (en vec->list) (uk вектор-у-список) (ukr вектор-у-список) (sa samūha-śreṇī candidate))
  (01110110 (en vec-from-list) (uk вектор-із-списку) (ukr вектор-із-списку) (sa śreṇī-samūha candidate))
  (01110111 (en is-fact?) (uk факт?) (ukr факт?) (sa jñāna-satya? candidate))
  (01111000 (en describe) (uk описати) (ukr описати) (sa varṇana candidate))
  (01111001 (en collect-facts-about) (uk зібрати-факти-про) (ukr зібрати-факти-про) (sa jñāna-saṅgraha candidate))
  (01111010 (en contains-atom?) (uk атом-у-списку?) (ukr атом-у-списку?) (sa aṇu-sambaddha? candidate))
  (01111011 (en forward-in) (uk пряме-виведення) (ukr пряме-виведення) (sa abhimukha-anumāna candidate))
  (01111100 (en reason-in) (uk логічний-висновок) (ukr логічний-висновок) (sa anumāna candidate))
  (01111101 (en check-conflict) (uk конфлікт?) (ukr є-конфлікт? candidate) (sa virodha-parīkṣā candidate))
  (01111110 (en module-known?) (uk модуль-відомий?) (ukr модуль-відомий?) (sa — missing))
  (01111111 (en module-clauses-now) (uk поточні-клаузи-модуля) (ukr поточні-клаузи-модуля) (sa — missing))
  (10000000 (en prove-goal) (uk довести-мету) (ukr довести-мету) (sa siddhi-sādhana candidate))
  (10000001 (en prove-goals) (uk довести-мети) (ukr довести-мети) (sa siddhi-sādhana-sarva candidate))
  (10000010 (en explain-proof) (uk пояснити-доведення) (ukr пояснити-доведення) (sa siddhi-vyākhyā candidate))
  (10000011 (en source-of) (uk джерело-доведення) (ukr джерело-доведення) (sa siddhi-mūla candidate))
  (10000100 (en provenance) (uk походження) (ukr походження) (sa utpatti candidate))
  (10000101 (en reason) (uk міркування) (ukr міркування) (sa tarka candidate))
  (10000110 (en reason-explain) (uk пояснити-міркування) (ukr пояснити-міркування) (sa tarka-vyākhyā candidate))
  (10000111 (en unify) (uk уніфікувати) (ukr уніфікувати) (sa ekīkaraṇa candidate))
  (10001000 (en logic-var) (uk логічна-змінна) (ukr логічна-змінна) (sa tarka-cihna candidate))
  (10001001 (en var?) (uk змінна?) (ukr змінна?) (sa cihna? candidate))
  (10001010 (en apply-subst) (uk підставити) (ukr підставити) (sa pratyāroha candidate))
  (10001011 (en walk) (uk розіменувати) (ukr розіменувати) (sa vicāraṇa-gamana candidate))
  (10001100 (en occurs-check) (uk змінна-зустрічається?) (ukr змінна-зустрічається?) (sa parivṛtti-parīkṣā candidate))
  (10001101 (en claim?) (uk твердження?) (ukr твердження?) (sa pratyaya? candidate))
  (10001110 (en claim-statement) (uk зміст-твердження) (ukr зміст-твердження) (sa pratyaya-vākya candidate))
  (10001111 (en claim-review) (uk стан-розгляду-твердження) (ukr стан-розгляду-твердження) (sa pratyaya-parīkṣā candidate))
  (10010000 (en evidence?) (uk доказ?) (ukr доказ?) (sa pramāṇa? candidate))
  (10010001 (en evidence-method) (uk метод-доказу) (ukr метод-доказу) (sa pramāṇa-vidhi candidate))
  (10010010 (en evidence-outcome) (uk результат-доказу) (ukr результат-доказу) (sa pramāṇa-phala candidate))
  (10010011 (en observation?) (uk спостереження?) (ukr спостереження?) (sa pratyakṣa? candidate))
  (10010100 (en observation-statement) (uk зміст-спостереження) (ukr зміст-спостереження) (sa pratyakṣa-vākya candidate))
  (10010101 (en intent?) (uk намір?) (ukr намір?) (sa saṅkalpa? candidate))
  (10010110 (en intent-goal) (uk мета-наміру) (ukr мета-наміру) (sa saṅkalpa-lakṣya candidate))
  (10010111 (en supporting-evidence) (uk підтримувальний-доказ) (ukr підтримувальний-доказ) (sa sahāya-pramāṇa candidate))
  (10011000 (en identity) (uk без-змін) (ukr повернути-без-змін candidate) (sa svabhāva candidate))
  (10011001 (en gensym) (uk генерувати-символ) (ukr створити-унікальний-символ candidate) (sa nāman-nirmāṇa candidate))
  (10011010 (en and) (uk та) (ukr та) (sa — missing))
  (10011011 (en or) (uk або) (ukr або) (sa — missing))
  (10011100 (en let) (uk нехай) (ukr нехай) (sa — missing))
  (10011101 (en let*) (uk нехай*) (ukr нехай-послідовно candidate) (sa — missing))
  (10011110 (en — compatibility-only) (uk — compatibility-only) (ukr ланцюжок-першого-аргументу candidate) (sa — compatibility-only) (sym -> compatibility-only))
  (10011111 (en — compatibility-only) (uk — compatibility-only) (ukr ланцюжок-останнього-аргументу candidate) (sa — compatibility-only) (sym ->> compatibility-only))
  (10100000 (en json-parse compatibility-only) (uk — compatibility-only) (ukr розібрати-текст-формату-джейсон candidate) (sa — compatibility-only))
  (10100001 (en sha256-hex compatibility-only) (uk — compatibility-only) (ukr обчислити-хеш-ша-256-тексту-у-шістнадцятковому-записі candidate) (sa — compatibility-only))
  (10100010 (en process-run) (uk запустити-процес candidate) (ukr запустити-процес candidate) (sa — missing))
  (10100011 (en tcp-read) (uk прочитати-текст-з-з'єднання-протоколу-керування-передаванням candidate) (ukr прочитати-текст-з-з'єднання-протоколу-керування-передаванням candidate) (sa — missing))
  (10100100 (en tcp-write) (uk записати-текст-у-з'єднання-протоколу-керування-передаванням candidate) (ukr записати-текст-у-з'єднання-протоколу-керування-передаванням candidate) (sa — missing))
  (10100101 (en tcp-listen) (uk слухати-порт-протоколу-керування-передаванням candidate) (ukr слухати-порт-протоколу-керування-передаванням candidate) (sa — missing))
  (10100110 (en read-file) (uk прочитати-файл candidate) (ukr прочитати-файл candidate) (sa — missing))
  (10100111 (en write-file) (uk записати-файл candidate) (ukr записати-файл candidate) (sa — missing))
